version: '2.1'
services:

    zookeeper:
        image: zookeeper:3.4.9
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zoo1:2888:3888
        volumes:
            - ./zk-single-kafka-single/zoo1/data:/data
            - ./zk-single-kafka-single/zoo1/datalog:/datalog
        networks:
            - dp-api-tests

    kafka:
        image: confluentinc/cp-kafka:3.2.0
        hostname: kafka
        ports:
            - "9093:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
        depends_on:
            - zookeeper
        networks:
            - dp-api-tests

    mongo:
        image: 'mongo:3.4'
        container_name: 'mongo'
        ports:
            - '27100:27017'
        networks:
            - dp-api-tests

    neo4j:
        environment:
            - NEO4J_AUTH=none
        image: 'neo4j:3.4.1'
        container_name: 'neo4j'
        ports:
            - '7688:7687'
        networks:
            - dp-api-tests

    auth_api:
        container_name: 'zebedee'
        build: ./auth-api
        working_dir: /go/src/github.com/ONSdigital/dp-auth-api-stub
        command: bash -c "make debug"
        ports:
            - '8082:8082'
        networks:
            - dp-api-tests

    dataset_api_publishing:
        container_name: dataset_api_publishing
        build: ./dataset-api
        working_dir: /go/src/github.com/ONSdigital/dp-dataset-api
        command: bash -c "git pull && git checkout ${DATASET_API_BRANCH} && make acceptance-publishing"
        ports:
            - '22000:22000'
        depends_on:
            - 'mongo'
            - 'kafka'
            - 'neo4j'
            - 'auth_api'
        environment:
            - HEALTHCHECK_INTERVAL=60s
            - KAFKA_ADDR=kafka:9092
            - MONGODB_BIND_ADDR=mongodb://mongo:27017
            - NEO4J_BIND_ADDRESS=bolt://neo4j:7687
            - ZEBEDEE_URL=zebedee:8082
            #- DATASET_API_URL=http:localhost:22000
        networks:
            - dp-api-tests

    dataset_api_publishing_tests:
        container_name: 'dataset-api-publishing-tests'
        depends_on:
            - 'dataset_api_publishing'
        networks:
            - dp-api-tests
        environment:
            - MONGODB_BIND_ADDR=mongodb://mongo:27017
            - KAFKA_ADDR=kafka:9092
            - NEO4J_BIND_ADDR=bolt://neo4j:7687
            - DATASET_API_URL=http://dataset_api_publishing:22000
        build: ./dataset-api-publishing-tests
        working_dir: /go/src/github.com/ONSdigital/dp-api-tests/publishing/datasetAPI
        command: bash -c "git pull && git checkout feature/fix-basic-tests && sleep 10 && HUMAN_LOG=1 go test ./..."


networks:
    dp-api-tests:
        driver: bridge
